### ISSUE TITLE
[QA]:  Github 권한 요청 이름 수정 

### ISSUE THREAD

**Issue by Redish03** [pknu-wap/WAPP#135]
### 작업 사항

최초 로그인 및 회원가입 진행 할 때, 권한 요청 페이지에서 이름이 Jinho Jung 에서 WAPP 로 수정

아래 사진 첨부 참고

### Todo

- [x] 버그 수정 

### 기타사항

![image](https://github.com/pknu-wap/WAPP/assets/98575563/d4ba60f5-7597-4def-8933-95b95eb73ff5)

**Comment by jeongjaino** [comment]
논의 필요. 

@tgyuuAn 

해당 JeongJinHo는 개발자 이름이라, 설정에서 변경할 수 없음. 

기본적으로 Github Social Login은 Github Developer Settings에서 권한 토큰을 발급함,

Developer Settings는 개인 개발자 혹은 조직에서 생성할 수 있음.

Jeong JinHo를 숨기기 위해서 최선의 대안은 WAP Organization에서 토큰을 발급해서 
기존 Jeong JinHo를 WAP으로 변경하는 것이 대안이 됨. 

태규상 의견 남겨주세요 ! 
기존 Jeong JinHo로 간다 vs pknu-wap으로 간다

아마 한다면, 회장님께 허락을 구해야겠네요

**Comment by tgyuuAn** [comment]
@jeongjaino WAPP가 가장 좋을 것 같으나,

WAPP의 본질이 WAP이기에 PKNU-wap이 더 좋을 것 같네요...!
