### ISSUE TITLE
[QA]: 행사가 종료된 후, 설문 조사 가능

### ISSUE THREAD

**Issue by gjsk132** [pknu-wap/WAPP#137]
### 작업 사항

이미 끝난 행사에 한해서 설문에 참가할 수 있도록 수정

### Todo

- [ ] 설문 기간 수정

**Comment by jeongjaino** [comment]
해당 이슈는 아마 설문 데드라인인 넘긴 이슈인것 같아요 

로직을 확인해봤는데, 
행사 날짜와 무관하고 운영진이 설정한 설문 데드라인을 넘기는 경우에만 설문 목록에 표시가 안됩니다.

**Comment by jeongjaino** [comment]
com/wap/wapp/feature/survey/SurveyViewModel.kt 참고
