### ISSUE TITLE
[FEATURE]: 피그마 서브 페이지 UI/UX 구현

### ISSUE THREAD

**Issue by tgyuuAn** [pknu-wap/WAPP#7]
### 작업 사항

피그마로 UI/UX 먼저 구현하기.

<a href="https://www.figma.com/file/ldfJcNruLXpb7e41P7LK3O/Untitled?type=design&node-id=1-4&mode=design&t=NANpCaNcx11N6yjJ-0">링크</a>

### Todo

- [x] 스플래쉬 화면
- [x] 로그인 화면  
- [x] 정보 입력 화면 
- [x] 마이페이지 화면 
- [x] 메인 페이지 화면 

### 기타사항
메인 페이지 - 달력 / 공지사항 리스트

**Comment by tgyuuAn** [comment]
![image](https://github.com/pknu-wap/WAPP/assets/116813010/245c01d1-d895-4f8d-81ce-37b8d4101f18)

저희 놀고 있지 않습니다... 

UI짜는 중일 뿐...

**Comment by alstjr7437** [comment]
왜 로고가 고양이인가요!
